### ISSUE TITLE
auto submit new meteor website

### ISSUE THREAD

**Issue by acemtp** [bakery/meteor-spotting#2]
I work on projects that are not already released and I don't want your tool to auto share the url of these private meteor projects.

When your extension detects a new meteor website that were never spotted, you should ask the user if he wants to add it.

If the meteor website is already known by your website, then it's no problem to auto +1 it.

Sadly (because I really like your project), I had to uninstall your extension because of this problem.

**Comment by callmephilip** [comment]
Sorry for the inconvenience. The goal with spotting was to make it as seamless as possible for all the participants which can obviously back fire (as described in your particular case). I think we will keep it this way at least for now.

**Comment by dandv** [comment]
How about a simple option to ignore `:3000` sites, if not a list as mentioned in #4?
